apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging-{{$.Values.clusterName}}
  namespace: argocd
spec:
  project: default
  sources:
  - chart: nginx-ingress-controller
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 11.3.9
    helm:
      valueFiles:
      - $values/environment-promotion/variants/non-prod/nginx-values.yaml
      - $values/environment-promotion/envs/staging/nginx-version.yaml
      - $values/environment-promotion/base/nginx-common.yaml
  - repoURL: 'https://github.com/jp-gouin/gitops-at-scale-cb.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: {{$.Values.destCluster}}
    namespace: infra
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true